# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format:
  body_listener: true
  format_listener:
    rules:
      - { path: ^/, fallback_format: json, priorities: [json] }
  param_fetcher_listener: true
  exception:
    enabled: true
  view:
    view_response_listener: force
    formats:
      json: true
