nelmio_api_doc:
    documentation:
        info:
            title: Sample TODO App API
            description: Just for demo purposes!
            version: 0.1.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$|/doc.json$) # Accepts routes under /api except /api/doc
