version: "3"

services:
  db:
    image: 'bitnami/mongodb:latest'
    restart: always
    network_mode: bridge
    hostname: db.docker
    expose:
      - 27017
    ports:
      - "27071:27071"
#    volumes:
#      - ./var/db:/bitnami
    environment:
        - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
        - MONGODB_USERNAME=${MONGODB_USERNAME}
        - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        - MONGODB_DATABASE=${MONGODB_DATABASE}
  mongo-express:
    image: mongo-express
    restart: always
    network_mode: bridge
    links:
      - db
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8081:8081"
    expose:
      - 8081
  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
      context: ./
    expose:
      - 80
    volumes:
      - .:/app
      - ~/.bash_history:/root/.bash_history
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      WEB_ALIAS_DOMAIN: ${PROJECT_NAME}
      WEB_DOCUMENT_ROOT: /app/public/
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: Europe/Warsaw
      PHP_DEBUGGER: xdebug
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 1
      XDEBUG_REMOTE_PORT: 9090
      XDEBUG_REMOTE_HOST: 192.168.1.129
    links:
      - db
    network_mode: bridge
    restart: always
