tasks:
    type: rest
    resource: App\Controller\TaskController
    prefix: api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }